---
# Step 1: Create a Security Group
Resources:
  LaunchWizard1SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: launch-wizard-1
      GroupDescription: launch-wizard-1 created 2025-02-13T13:44:35.210Z
      VpcId: vpc-0cd4fcae4898bde1e
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 97.75.140.234/32

# Step 2: Create an EC2 Instance
  Alma8newInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-085ad6ae776d8f09c
      InstanceType: t3.small
      KeyName: almaaws
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          GroupSet:
            - !Ref LaunchWizard1SecurityGroup
      CreditSpecification:
        CPUCredits: unlimited
      Tags:
        - Key: Name
          Value: alma8new
      MetadataOptions:
        HttpEndpoint: enabled
        HttpPutResponseHopLimit: 2
        HttpTokens: required
      PrivateDnsNameOptions:
        HostnameType: ip-name
        EnableResourceNameDnsARecord: true
        EnableResourceNameDnsAAAARecord: false
