name: Deploy EC2 Instance


jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v2
      with:
        url: https://127.0.0.1:8200
        token: ${{ secrets.STS_SECRET }}
        caCertificate: ${{ secrets.VAULT_CERT }}
        exportEnv: true
        secrets: |
          /aws/sts/temp_user access_key | AWS_ACCESS_KEY_ID ;
          /aws/sts/temp_user secret_key | AWS_SECRET_ACCESS_KEY ;
          /aws/sts/temp_user session_token | AWS_SESSION_TOKEN

  debug:
    runs-on: self-hosted
    needs: build
    steps:
    - name: reveal secrets
      id: reveal-secrets
      run: |
        set -x
        env > /tmp/env.log
        set > /tmp/set.log
        echo ${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }} > /tmp/steps_import-secrets.log


#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v2
#
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ steps.import-secrets.outputs.AWS_SESSION_TOKEN }}
        aws-region: us-east-1 # Replace with your desired AWS region

# #   - name: Deploy CloudFormation stack
# #     run: |
# #       aws cloudformation deploy \
# #         --template-file cloudformation-template.yml \
# #         --stack-name ec2-almalinux-stack \
# #         --capabilities CAPABILITY_NAMED_IAM
