name: Deploy EC2 Instance

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Import Secrets
      uses: hashicorp/vault-action@v3.1.0
      with:
        url: https://127.0.0.1:8200
        tlsSkipVerify: true
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          aws/creds/my-role  access_key | AWS_ACCESS_KEY_ID;
          aws/creds/my-role  secret_key | AWS_SECRET_ACCESS_KEY
  
  
  deploy:
    runs-on: ubuntu-latest

    steps:
#    - name: Debug vault
#      run: |
#        echo "${{ env.AWS_ACCESS_KEY_ID }}" > myfile
#        cat myfile
      
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your desired AWS region

 #   - name: Deploy CloudFormation stack
 #     run: |
 #       aws cloudformation deploy \
 #         --template-file cloudformation-template.yml \
 #         --stack-name ec2-almalinux-stack \
 #         --capabilities CAPABILITY_NAMED_IAM
