name: Deploy EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3.1.0
      with:
        url: https://127.0.0.1:8200
        tlsSkipVerify: true
#        token: ${{ secrets.VAULT_TOKEN }}
        token: ${{ secrets.MYGITHUB_TOKEN }}
        exportEnv: true
        secrets: |
          /aws/creds/my-role * | AWS_ ;

  debug:
    runs-on: self-hosted
    needs: build
    steps:
    - name: reveal secrets
      id: reveal-secrets
      run: |
        set -x
        env > /tmp/env.log
        set > /tmp/set.log
        echo '${{ toJson(needs.build.outputs) }}' > /tmp/needs_build.log
        echo '${{ toJson(needs.import-secrets.outputs) }}' > /tmp/needs_import-secrets.log
        echo '${{ toJson(steps.build.outputs) }}' > /tmp/steps_build.log
        echo '${{ toJson(steps.import-secrets.outputs) }}' > /tmp/steps_import-secrets.log


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: $AWS_KEY
        aws-secret-access-key: $AWS_SECRET
        aws-region: us-east-1 # Replace with your desired AWS region

 #   - name: Deploy CloudFormation stack
 #     run: |
 #       aws cloudformation deploy \
 #         --template-file cloudformation-template.yml \
 #         --stack-name ec2-almalinux-stack \
 #         --capabilities CAPABILITY_NAMED_IAM
