name: Deploy EC2 Instance

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@v3.1.0
      with:
        url: https://127.0.0.1:8200
        tlsSkipVerify: true
#        token: ${{ secrets.VAULT_TOKEN }}
        token: ${{ secrets.MYGITHUB_TOKEN }}
        exportEnv: false
        secrets: |
          /aws/creds/my-role  access_key | AWS_ACCESS_KEY_ID ;
          /aws/creds/my-role  secret_key | AWS_SECRET_ACCESS_KEY
  
  debug:
    runs-on: self-hosted
    steps:
    - name: reveal secrets
      id: reveal-secrets
      run: |
        logger '${{ toJson(steps.import-secrets.outputs) }}'
        
#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Debug vault
#      run: |
#       sleep 0
#       set -x
#       echo '${{ toJson(steps.import-secrets.outputs.AWS_ACCESS_KEY_ID) }}' \| base64 -w0; echo

#       if [ -n ${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }} ]; then echo not empty; else  echo empty; fi

#        echo "${{ toJson(steps.import-secrets.outputs) }}" >> secrets.json
#        cat secrets.json
#        ACCESS_KEY_ID="${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}"
#        SECRET_ACCESS_KEY="{{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}"
      
    - name: Checkout repository
      uses: actions/checkout@v2

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-access-key-id: ${{ steps.import-secrets.outputs.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ steps.import-secrets.outputs.AWS_SECRET_ACCESS_KEY }}
#        aws-region: us-east-1 # Replace with your desired AWS region

 #   - name: Deploy CloudFormation stack
 #     run: |
 #       aws cloudformation deploy \
 #         --template-file cloudformation-template.yml \
 #         --stack-name ec2-almalinux-stack \
 #         --capabilities CAPABILITY_NAMED_IAM
