name: Deploy EC2 Instance

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::343218193807:role/newer_oidc_role
          aws-region: us-east-1

      - name: Azure Login
        uses: azure/login@v2.2.0
        with:
          client-id:  ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#          auth-type: IDENTITY


          
