name: Deploy EC2 Instance

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        
      - name: Deploy CloudFormation stack
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::343218193807:role/newer_oidc_role
          aws-region: us-east-1

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yml \
            --stack-name ec2-almalinux-stack \
            --capabilities CAPABILITY_NAMED_IAM


          
